<?php

########################################################################
# Extension Manager/Repository config file for ext: "php_parser_api"
#
# Auto generated by Extension Builder 2012-03-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PHP Parser Wrapper',
	'description' => 'Tool to convert PHP classes in objects, modify them and get a string representation of the new source code',
	'category' => 'misc',
	'author' => 'Nico de Haen',
	'author_email' => 'mail@ndh-websolutions.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>